=== consiglionazionaledellericerche/alfresco-amps/src/main/resources/alfresco/model/modelSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.alfresco.org/model/dictionary/1.0" xmlns:dd="http://www.alfresco.org/model/dictionary/1.0" elementFormDefault="qualified" version="0.1">

    <xs:annotation>
    	<xs:documentation>Alfresco Data Dictionary Schema - DRAFT</xs:documentation>
    </xs:annotation>
    
    <xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description" type="xs:string" maxOccurs="1" minOccurs="0"/>
				<xs:element name="author" type="xs:string" maxOccurs="1" minOccurs="0"/>
				<xs:element name="published" type="xs:date" maxOccurs="1" minOccurs="0"/>
				<xs:element name="version" type="xs:string" maxOccurs="1" minOccurs="0"/>
				<xs:element name="imports" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="import" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attributeGroup ref="dd:namespaceDefinition"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="namespaces">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="namespace" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attributeGroup ref="dd:namespaceDefinition"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				
				<xs:element name="constraints" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constraint" maxOccurs="unbounded" minOccurs="1" type="dd:constraintType" />
							
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="property-types" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="property-type" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:group ref="dd:TextualDescription"/>
										<xs:element name="analyser-class" maxOccurs="1" minOccurs="0"/>
										<xs:element name="java-class" maxOccurs="1" minOccurs="0"/>
									</xs:sequence>
									<xs:attributeGroup ref="dd:name"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="types" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type" type="dd:type" maxOccurs="unbounded" minOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="aspects" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="aspect" type="dd:aspect" maxOccurs="unbounded" minOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attributeGroup ref="dd:name"/>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="class">
		<xs:sequence>
			<xs:group ref="dd:TextualDescription"></xs:group>
			<xs:element name="parent" type="xs:string" maxOccurs="1" minOccurs="0" />
			<xs:element name="archive" type="xs:boolean" minOccurs="0" maxOccurs="1"></xs:element>
			
			<xs:element name="properties" maxOccurs="1" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="property" type="dd:property"
							maxOccurs="unbounded" minOccurs="1" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="associations" maxOccurs="1"
				minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="association"
							type="dd:association" maxOccurs="unbounded" minOccurs="0" />
						<xs:element name="child-association"
							type="dd:childAssociation" maxOccurs="unbounded" minOccurs="0" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="overrides" maxOccurs="1" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="propertyOverrides"
							maxOccurs="1" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="property"
										type="dd:propertyOverride" maxOccurs="unbounded"
										minOccurs="1" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="dd:name" />
	</xs:complexType>


    <!-- constraints types -->
    <xs:complexType name="constraintType">
      <xs:sequence>
        <xs:element name="parameter" type="dd:parameterType" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="LENGTH"></xs:enumeration>
      		<xs:enumeration value="LIST"></xs:enumeration>
      		<xs:enumeration value="MINMAX"></xs:enumeration>
      		<xs:enumeration value="REGEX"></xs:enumeration>
      	  </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      
    </xs:complexType>

    <xs:complexType name="parameterType">
      <xs:choice>
        <xs:element name="list" type="dd:listType" />
        <xs:element name="value" type="xs:string"  />
      </xs:choice>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="listType">
      <xs:sequence>
        <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
    
    <!-- end of constraints types -->

	<xs:complexType name="property">
		<xs:sequence>
			<xs:group ref="dd:TextualDescription"/>
			<xs:element name="type" type="xs:string"/>
			<xs:element name="protected" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
			<xs:element name="mandatory" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:simpleContent>
                    	<xs:extension base="xs:boolean">
                      		<xs:attribute name="enforced" type="xs:boolean" />
                    	</xs:extension>
                  	</xs:simpleContent>
                </xs:complexType>
			</xs:element>
			<xs:element name="constraints" maxOccurs="1" minOccurs="0">
			<xs:complexType>
			  <xs:sequence>
			    <xs:element name="constraint" minOccurs="1" maxOccurs="unbounded">
			      <xs:complexType>
			      <xs:attribute name="ref" />
			      </xs:complexType>			      
			    </xs:element>
			  </xs:sequence>
			</xs:complexType>
			</xs:element>
			
			
			<xs:element name="multiple" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
			<xs:element name="default" type="xs:anyType" maxOccurs="1" minOccurs="0"/>
			<xs:element name="index" maxOccurs="1" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="atomic" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
						<xs:element name="stored" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
						<xs:element name="tokenised" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
					</xs:sequence>
					<xs:attribute name="enabled" type="xs:boolean" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="dd:name"/>
	</xs:complexType>

	<xs:complexType name="type">
		<xs:complexContent>
			<xs:extension base="dd:class">
				<xs:sequence>
					<xs:element name="mandatory-aspects" maxOccurs="1" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="aspect" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="aspect">
		<xs:complexContent>
			<xs:extension base="dd:class">
				<xs:sequence>
					<xs:element name="mandatory-aspects" maxOccurs="1" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="aspect" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="association">
		<xs:sequence>
			<xs:group ref="dd:TextualDescription"></xs:group>
			<xs:element name="source" maxOccurs="1" minOccurs="0">				<xs:complexType>					<xs:sequence>						<xs:group ref="dd:role"></xs:group>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="target">				<xs:complexType>					<xs:sequence>						<xs:element name="class" type="xs:string"></xs:element>
						<xs:group ref="dd:role"></xs:group>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="dd:name"/>
	</xs:complexType>

	<xs:complexType name="childAssociation">
		<xs:complexContent>
			<xs:extension base="dd:association">
				<xs:sequence>
					<xs:element name="child-name" type="xs:string" maxOccurs="1" minOccurs="0"/>
					<xs:element name="duplicate" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
					<xs:element name="propagateTimestamps" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:group name="role">
		<xs:sequence>
			<xs:element name="role" type="xs:string" maxOccurs="1" minOccurs="0"/>
			<xs:element name="mandatory" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
			<xs:element name="many" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
	</xs:group>

	<xs:complexType name="propertyOverride">
		<xs:sequence>
			<xs:element name="mandatory" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
			<xs:element name="default" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attributeGroup ref="dd:name"/>
	</xs:complexType>

	<xs:attributeGroup name="namespaceDefinition">
		<xs:attribute name="uri" type="xs:string" use="required" />
		<xs:attribute name="prefix" type="xs:string" use="required" />
	</xs:attributeGroup>

	<xs:attributeGroup name="name">
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:attributeGroup>

	<xs:group name="TextualDescription">
		<xs:sequence>
			<xs:element name="title" type="xs:string" maxOccurs="1" minOccurs="0"/>
			<xs:element name="description" type="xs:string" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
	</xs:group>

</xs:schema>

=== consiglionazionaledellericerche/alfresco-amps/alfresco-amp/sigla-extension-content-model/src/main/resources/alfresco/model/sigla/dipendentiModel.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!-- Definition of new Model -->
<model name="emp:contentmodel" 
	xmlns="http://www.alfresco.org/model/dictionary/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.alfresco.org/model/dictionary/1.0 modelSchema.xsd">

	<!-- Optional meta-data about the model -->
	<description>SIGLA extension Content Model - Dipendenti</description>
	<author>Marco Spasiano</author>
	<version>1.3</version>

	<!--
		Imports are required to allow references to definitions in other
		models
	-->
	<imports>
		<!-- Import Alfresco Dictionary Definitions -->
		<import uri="http://www.alfresco.org/model/dictionary/1.0" prefix="d" />
		<!-- Import Alfresco Content Domain Model Definitions -->
		<import uri="http://www.alfresco.org/model/content/1.0" prefix="cm" />
	</imports>

	<!-- Introduction of new namespaces defined by this model -->
	<namespaces>
		<namespace uri="http://www.cnr.it/emp/1.0/" prefix="emp" />
	</namespaces>
	<aspects>
		<aspect name="emp:cf">
			<title>Codice fiscale del dipendente</title>
			<properties>
				<property name="emp:cfcodice">
					<title>Codice fiscale</title>
					<type>d:text</type>
				</property>
			</properties>
		</aspect>
		<aspect name="emp:matricola">
			<title>Matricola del dipendente</title>
			<properties>
				<property name="emp:matricolacodice">
					<title>Matricola</title>
					<type>d:text</type>
				</property>
			</properties>
		</aspect>
	</aspects>
</model>

=== consiglionazionaledellericerche/alfresco-amps/alfresco-amp/sigla-extension-content-model/src/main/resources/alfresco/model/sigla/struttura-organizzativaModel.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!-- Definition of new Model -->
<model name="strorg:contentmodel" xmlns="http://www.alfresco.org/model/dictionary/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.alfresco.org/model/dictionary/1.0 modelSchema.xsd">

	<!-- Optional meta-data about the model -->
	<description>SIGLA extension Content Model - Struttura Organizzativa</description>
	<author>Marco Spasiano</author>
	<version>1.3</version>

	<!--
		Imports are required to allow references to definitions in other
		models
	-->
	<imports>
		<!-- Import Alfresco Dictionary Definitions -->
		<import uri="http://www.alfresco.org/model/dictionary/1.0" prefix="d" />
		<!-- Import Alfresco Content Domain Model Definitions -->
		<import uri="http://www.alfresco.org/model/content/1.0" prefix="cm" />
	</imports>

	<!-- Introduction of new namespaces defined by this model -->
	<namespaces>
		<namespace uri="http://www.cnr.it/1.0/" prefix="cnr" />
		<namespace uri="http://www.cnr.it/str/org/1.0/" prefix="strorg" />
		<namespace uri="http://www.cnr.it/str/org/cds/1.0/" prefix="strorgcds" />
		<namespace uri="http://www.cnr.it/str/org/uo/1.0/" prefix="strorguo" />
		<namespace uri="http://www.cnr.it/str/org/cdr/1.0/" prefix="strorgcdr" />
	</namespaces>
	
	<types>
		<type name="cnr:envelopedDocument">
			<title>Documento firmato Digitalmente</title>
			<description>Documento firmato Digitalmente</description>
			<parent>cm:content</parent>
			<associations>
				<association name="cnr:signedDocumentAss">
					<source>
						<mandatory>false</mandatory>
						<many>false</many>
					</source>
					<target>
						<class>cm:content</class>
						<mandatory>true</mandatory>
						<many>false</many>
					</target>
				</association>
			</associations>
		</type>
	</types>		
	<aspects>
		<aspect name="cnr:signedDocument">
			<title>Documento firmato Digitalmente</title>
		</aspect>
		<aspect name="strorg:cds">
			<title>CdS di riferimento</title>
			<properties>
				<property name="strorgcds:codice">
					<title>CdS di riferimento</title>
					<type>d:text</type>
				</property>
				<property name="strorgcds:descrizione">
					<title>Descrizione CdS di riferimento</title>
					<type>d:text</type>
				</property>
			</properties>
		</aspect>
		<aspect name="strorg:uo">
			<title>Uo di riferimento</title>
			<properties>
				<property name="strorguo:codice">
					<title>Uo di riferimento</title>
					<type>d:text</type>
				</property>
				<property name="strorguo:descrizione">
					<title>Descrizione Uo di riferimento</title>
					<type>d:text</type>
				</property>
			</properties>
		</aspect>
		<aspect name="strorg:cdr">
			<title>CdR di riferimento</title>
			<properties>
				<property name="strorgcdr:codice">
					<title>CdR di riferimento</title>
					<type>d:text</type>
				</property>
				<property name="strorgcdr:descrizione">
					<title>Descrizione CdR di riferimento</title>
					<type>d:text</type>
				</property>
			</properties>
		</aspect>

	</aspects>
</model>
